name = "MPITestImages"
uuid = "67a05f95-e8e3-406b-b1ec-9f1919b23209"
authors = ["Various contributors"]
version = "0.1.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
Compat = "3"
DocStringExtensions = "0.8"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
